
insert into patologia (id,descripcion,grupo,estado) values 
(newid(),'Ninguna','reciennacido','A'),
(newid(),'Memb. Hialina','reciennacido','A'),
(newid(),'Sind. Aspirat','reciennacido','A'),
(newid(),'Apnea','reciennacido','A'),
(newid(),'Otros Sdr','reciennacido','A'),
(newid(),'Hemorragia','reciennacido','A'),
(newid(),'Hiperbilirrub.','reciennacido','A'),
(newid(),'Otros Hematol.','reciennacido','A'),
(newid(),'Infecciones','reciennacido','A'),
(newid(),'Defectos Congénitos','reciennacido','A'),
(newid(),'Neurológicas','reciennacido','A'),
(newid(),'Metab / Nutric.','reciennacido','A'),
(newid(),'Otras','reciennacido','A'),

(newid(),'Ninguna','parto','A'),
(newid(),'Emb. Múltiple','parto','A'),
(newid(),'Hipert. Previa','parto','A'),
(newid(),'Pre Eclampsia','parto','A'),
(newid(),'Eclampsia','parto','A'),
(newid(),'Cardiopatia','parto','A'),
(newid(),'Diabetes','parto','A'),
(newid(),'Infección Urinaria','parto','A'),
(newid(),'Otras Infecciones','parto','A'),
(newid(),'Parasitosis','parto','A'),
(newid(),'RCIU','parto','A'),
(newid(),'Anem. Parto Pre.','parto','A'),
(newid(),'Desprop. Cef. Pelv.','parto','A'),
(newid(),'Hemorragia 1er Trimestre','parto','A'),
(newid(),'Hemorragia 2do Trimestre','parto','A'),
(newid(),'Hemorragia 3er Trimestre','parto','A'),

(newid(),'Anemia','postparto','A'),
(newid(),'Rot. Pre Memb.','postparto','A'),
(newid(),'Infeccion Puerp.','postparto','A'),
(newid(),'Hemorragia Puerp','postparto','A'),
(newid(),'Otras','postparto','A')